/* Static questions constant for form's question labels  */
const questions = [
    { label: 'WHAT WERE YOUR PRIMARY OBJECTIVES IN YOUR ROLE AND TO WHAT EXTENT DO YOU FEEL YOU ACHIEVED THEM?' },
    { label: 'WHAT ARE THREE THINGS THAT YOU DID WELL WITHIN THE LAST YEAR? WHY DO YOU BELIEVE YOU WERE SUCCESSFUL?' },
    { label: 'GIVE AN EXAMPLE OF A DIFFICULT SITUATION YOU HANDLED WELL AND THE STRENGTHS YOU USED TO ACHIEVE THAT END RESULT.' },
    { label: 'WHAT ARE THE ORGANISATIONAL ACTIVITIES YOU PERFORMED, APART FROM YOUR CURRENT ROLE?' },
    { label: 'WHAT JOB-SPECIFIC GOALS WOULD YOU LIKE TO ACCOMPLISH DURING THE UPCOMING EVALUATION PERIOD?' },
    { label: 'WHAT STEPS CAN YOUR MANAGER OR ORGANIZATION TAKE TO HELP YOU REACH THOSE GOALS?' },
    { label: "WHAT ARE ONE OR TWO EXAMPLES OF WAYS IN WHICH YOU'VE GROWN PROFESSIONALLY WITHIN THE LAST EVALUATION PERIOD?" },
    { label: "DO YOU FEEL THAT YOU SPENT ENOUGH TIME AND RESOURCES ON YOUR OWN PROFESSIONAL DEVELOPMENT? PLEASE EXPLAIN WHY YOU FEEL YOU DID OR DIDN'T." },
    { label: "WHAT CAREER GROWTH OR PROFESSIONAL GOALS DO YOU HOPE TO ACCOMPLISH IN THE NEXT YEAR?" },
    { label: "WHAT SUPPORT AND RESOURCES CAN THE COMPANY PROVIDE TO HELP YOU ACCOMPLISH THOSE GOALS?" },
];
export default questions;